server:
  port: 8091


# stater 配置参数
demo1:
  config:
    username: demo1
    password: 123456
    ip: 192.158.16.2
    port: 80

demo2:
  config:
    username: demo2
    password: 123456
    ip: 192.158.16.2
    port: 80
