server:
  port: 8084
  shutdown: graceful

spring:
  application:
    name: test-db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 4
      max-lifetime: 1800000
      connection-test-query: SELECT A FROM T_POOLPING

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
